// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: explorer/v1/explorer.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// 为某个枚举单独设置错误码
	ErrorReason_USER_NOT_FOUND  ErrorReason = 0
	ErrorReason_CONTENT_MISSING ErrorReason = 1
	ErrorReason_UNKNOWN         ErrorReason = 2
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "USER_NOT_FOUND",
		1: "CONTENT_MISSING",
		2: "UNKNOWN",
	}
	ErrorReason_value = map[string]int32{
		"USER_NOT_FOUND":  0,
		"CONTENT_MISSING": 1,
		"UNKNOWN":         2,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_explorer_v1_explorer_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_explorer_v1_explorer_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_explorer_v1_explorer_proto_rawDescGZIP(), []int{0}
}

type CreateFooRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateFooRequest) Reset() {
	*x = CreateFooRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_explorer_v1_explorer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFooRequest) ProtoMessage() {}

func (x *CreateFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_explorer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFooRequest.ProtoReflect.Descriptor instead.
func (*CreateFooRequest) Descriptor() ([]byte, []int) {
	return file_explorer_v1_explorer_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFooRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateFooReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CreateFooReply) Reset() {
	*x = CreateFooReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_explorer_v1_explorer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFooReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFooReply) ProtoMessage() {}

func (x *CreateFooReply) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_explorer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFooReply.ProtoReflect.Descriptor instead.
func (*CreateFooReply) Descriptor() ([]byte, []int) {
	return file_explorer_v1_explorer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFooReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateFooRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateFooRequest) Reset() {
	*x = UpdateFooRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_explorer_v1_explorer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFooRequest) ProtoMessage() {}

func (x *UpdateFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_explorer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFooRequest.ProtoReflect.Descriptor instead.
func (*UpdateFooRequest) Descriptor() ([]byte, []int) {
	return file_explorer_v1_explorer_proto_rawDescGZIP(), []int{2}
}

type UpdateFooReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateFooReply) Reset() {
	*x = UpdateFooReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_explorer_v1_explorer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFooReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFooReply) ProtoMessage() {}

func (x *UpdateFooReply) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_explorer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFooReply.ProtoReflect.Descriptor instead.
func (*UpdateFooReply) Descriptor() ([]byte, []int) {
	return file_explorer_v1_explorer_proto_rawDescGZIP(), []int{3}
}

type DeleteFooRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteFooRequest) Reset() {
	*x = DeleteFooRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_explorer_v1_explorer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFooRequest) ProtoMessage() {}

func (x *DeleteFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_explorer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFooRequest.ProtoReflect.Descriptor instead.
func (*DeleteFooRequest) Descriptor() ([]byte, []int) {
	return file_explorer_v1_explorer_proto_rawDescGZIP(), []int{4}
}

type DeleteFooReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteFooReply) Reset() {
	*x = DeleteFooReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_explorer_v1_explorer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFooReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFooReply) ProtoMessage() {}

func (x *DeleteFooReply) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_explorer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFooReply.ProtoReflect.Descriptor instead.
func (*DeleteFooReply) Descriptor() ([]byte, []int) {
	return file_explorer_v1_explorer_proto_rawDescGZIP(), []int{5}
}

type GetFooRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFooRequest) Reset() {
	*x = GetFooRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_explorer_v1_explorer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFooRequest) ProtoMessage() {}

func (x *GetFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_explorer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFooRequest.ProtoReflect.Descriptor instead.
func (*GetFooRequest) Descriptor() ([]byte, []int) {
	return file_explorer_v1_explorer_proto_rawDescGZIP(), []int{6}
}

type GetFooReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFooReply) Reset() {
	*x = GetFooReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_explorer_v1_explorer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFooReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFooReply) ProtoMessage() {}

func (x *GetFooReply) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_explorer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFooReply.ProtoReflect.Descriptor instead.
func (*GetFooReply) Descriptor() ([]byte, []int) {
	return file_explorer_v1_explorer_proto_rawDescGZIP(), []int{7}
}

type ListFooRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListFooRequest) Reset() {
	*x = ListFooRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_explorer_v1_explorer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFooRequest) ProtoMessage() {}

func (x *ListFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_explorer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFooRequest.ProtoReflect.Descriptor instead.
func (*ListFooRequest) Descriptor() ([]byte, []int) {
	return file_explorer_v1_explorer_proto_rawDescGZIP(), []int{8}
}

type ListFooReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListFooReply) Reset() {
	*x = ListFooReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_explorer_v1_explorer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFooReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFooReply) ProtoMessage() {}

func (x *ListFooReply) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_explorer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFooReply.ProtoReflect.Descriptor instead.
func (*ListFooReply) Descriptor() ([]byte, []int) {
	return file_explorer_v1_explorer_proto_rawDescGZIP(), []int{9}
}

var File_explorer_v1_explorer_proto protoreflect.FileDescriptor

var file_explorer_v1_explorer_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x6f, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x6f, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x66, 0x6f, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a,
	0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x6f, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a,
	0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x46,
	0x6f, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2a, 0x55, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e,
	0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x00, 0x1a, 0x04, 0xa8, 0x45, 0x94, 0x03,
	0x12, 0x19, 0x0a, 0x0f, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x4d, 0x49, 0x53, 0x53,
	0x49, 0x4e, 0x47, 0x10, 0x01, 0x1a, 0x04, 0xa8, 0x45, 0x90, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x32, 0xcc,
	0x02, 0x0a, 0x03, 0x46, 0x6f, 0x6f, 0x12, 0x58, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x6f, 0x6f, 0x12, 0x18, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x66, 0x6f, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x66, 0x6f, 0x6f, 0x2f, 0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x7d,
	0x12, 0x3d, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x12, 0x18, 0x2e,
	0x66, 0x6f, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x3d, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x12, 0x18, 0x2e, 0x66,
	0x6f, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34,
	0x0a, 0x06, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x12, 0x15, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x37, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x12,
	0x16, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x13, 0x5a,
	0x11, 0x66, 0x6f, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x6f, 0x6f, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_explorer_v1_explorer_proto_rawDescOnce sync.Once
	file_explorer_v1_explorer_proto_rawDescData = file_explorer_v1_explorer_proto_rawDesc
)

func file_explorer_v1_explorer_proto_rawDescGZIP() []byte {
	file_explorer_v1_explorer_proto_rawDescOnce.Do(func() {
		file_explorer_v1_explorer_proto_rawDescData = protoimpl.X.CompressGZIP(file_explorer_v1_explorer_proto_rawDescData)
	})
	return file_explorer_v1_explorer_proto_rawDescData
}

var file_explorer_v1_explorer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_explorer_v1_explorer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_explorer_v1_explorer_proto_goTypes = []interface{}{
	(ErrorReason)(0),         // 0: explorer.v1.ErrorReason
	(*CreateFooRequest)(nil), // 1: explorer.v1.CreateFooRequest
	(*CreateFooReply)(nil),   // 2: explorer.v1.CreateFooReply
	(*UpdateFooRequest)(nil), // 3: explorer.v1.UpdateFooRequest
	(*UpdateFooReply)(nil),   // 4: explorer.v1.UpdateFooReply
	(*DeleteFooRequest)(nil), // 5: explorer.v1.DeleteFooRequest
	(*DeleteFooReply)(nil),   // 6: explorer.v1.DeleteFooReply
	(*GetFooRequest)(nil),    // 7: explorer.v1.GetFooRequest
	(*GetFooReply)(nil),      // 8: explorer.v1.GetFooReply
	(*ListFooRequest)(nil),   // 9: explorer.v1.ListFooRequest
	(*ListFooReply)(nil),     // 10: explorer.v1.ListFooReply
}
var file_explorer_v1_explorer_proto_depIdxs = []int32{
	1,  // 0: explorer.v1.Foo.CreateFoo:input_type -> explorer.v1.CreateFooRequest
	3,  // 1: explorer.v1.Foo.UpdateFoo:input_type -> explorer.v1.UpdateFooRequest
	5,  // 2: explorer.v1.Foo.DeleteFoo:input_type -> explorer.v1.DeleteFooRequest
	7,  // 3: explorer.v1.Foo.GetFoo:input_type -> explorer.v1.GetFooRequest
	9,  // 4: explorer.v1.Foo.ListFoo:input_type -> explorer.v1.ListFooRequest
	2,  // 5: explorer.v1.Foo.CreateFoo:output_type -> explorer.v1.CreateFooReply
	4,  // 6: explorer.v1.Foo.UpdateFoo:output_type -> explorer.v1.UpdateFooReply
	6,  // 7: explorer.v1.Foo.DeleteFoo:output_type -> explorer.v1.DeleteFooReply
	8,  // 8: explorer.v1.Foo.GetFoo:output_type -> explorer.v1.GetFooReply
	10, // 9: explorer.v1.Foo.ListFoo:output_type -> explorer.v1.ListFooReply
	5,  // [5:10] is the sub-list for method output_type
	0,  // [0:5] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_explorer_v1_explorer_proto_init() }
func file_explorer_v1_explorer_proto_init() {
	if File_explorer_v1_explorer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_explorer_v1_explorer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFooRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_explorer_v1_explorer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFooReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_explorer_v1_explorer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFooRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_explorer_v1_explorer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFooReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_explorer_v1_explorer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFooRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_explorer_v1_explorer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFooReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_explorer_v1_explorer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFooRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_explorer_v1_explorer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFooReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_explorer_v1_explorer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFooRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_explorer_v1_explorer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFooReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_explorer_v1_explorer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_explorer_v1_explorer_proto_goTypes,
		DependencyIndexes: file_explorer_v1_explorer_proto_depIdxs,
		EnumInfos:         file_explorer_v1_explorer_proto_enumTypes,
		MessageInfos:      file_explorer_v1_explorer_proto_msgTypes,
	}.Build()
	File_explorer_v1_explorer_proto = out.File
	file_explorer_v1_explorer_proto_rawDesc = nil
	file_explorer_v1_explorer_proto_goTypes = nil
	file_explorer_v1_explorer_proto_depIdxs = nil
}
